[package]
name = "openai-api-integration"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
reqwest = { version = "0.12.8", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1.40.0", features = ["full"] }

